# config file version
apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  url: http://prometheus-service.monitoring.svc.cluster.local:8080
  access: proxy
  isDefault: true
  jsonData:
      timeInterval: "30s"
  editable: false